name: or-obj-detection

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit==10.1.243
  - kombu
  - flask
  - pip:
    - tensorflow-gpu==2.3.0rc0
    - opencv-python-headless==4.1.1.26
    - lxml
    - tqdm
    - absl-py
    - easydict
    - pillow
    - youtube-dl
    - pafy
    - python-vlc

