version: "3.7"

services:
  rabbitmq:
    build: RabbitMQ/. 
    hostname: "rabbitmq"
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "15674:15674"
    labels:
      NAME: "rabbitmq1"
  frontend:
    container_name: or-frontend
    build: config-fe/.
    stdin_open: true
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
  backend:
    container_name: or-backend
    build: back-end/.
    environment:
     - BACKEND_HOST=0.0.0.0
     - BACKEND_PORT=5000
    ports:
      - "5000:5000"
  object-detection:
    container_name: or-obj-detection
    restart: always
    image: or-obj-detection:latest
    build: yolo_object_detection/.
    environment:
      - RABBITMQ_URL="rabbitmq"
    links:
      - rabbitmq
    privileged: true
