version: "3.7"

services:
  rabbitmq:
    build: RabbitMQ/.
    image: or-rabbitmq:latest
    hostname: "rabbitmq"
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "15674:15674"
    labels:
      NAME: "rabbitmq1"
  frontend:
    container_name: or-frontend
    image: or-frontend:latest
    restart: always
    build: config-fe/.
    stdin_open: true
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
  backend:
    container_name: backend
    build: back-end/.
    hostname: backend
    environment:
      BACKEND_HOST: 0.0.0.0
      BACKEND_PORT: 5000
      MQTT_HOST: "localhost"
      MQTT_PORT: "1883"
      MQTT_CLIENT_ID: "or_od_1"
      MQTT_USERNAME: "CHANGEME"
      MQTT_PASSWORD: "CHANGEME"
    ports:
      - "5000:5000"
  object-detection:
    container_name: or-obj-detection
    restart: always
    image: or-obj-detection:latest
    build: yolo_object_detection/.
    environment:
      - RABBITMQ_URL=rabbitmq
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_MIG_CONFIG_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=:0.0
    devices:
      - /dev/snd
    links:
      - rabbitmq
    privileged: true
